---
apiVersion: v1
kind: Namespace
metadata:
  name: ctse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-management-deployment
  namespace: ctse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-management
  template:
    metadata:
      labels:
        app: cart-management
    spec:
      containers:
        - name: cart-management
          image: jayanisaumya/cartapi:latest
          ports:
            - containerPort: 3006
          envFrom:
            - configMapRef:
                name: cart-management-config


